name: CI

on:
  pull_request:

jobs:
  test:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        ref: ${{ github.sha }}
    # All the below is required because the repository with the action is private
    - name: Checkout tool
      uses: actions/checkout@v6
      with:
        repository: th2-net/ci-github-action
        ref: master
        token: ${{ secrets.PAT_CI_ACTION }}
        path: ci-github-action
    - name: Run CI action
      uses: ./ci-github-action
      with:
        ref: ${{ github.sha }}
